-- Faza Quiz (Q4): the student side. A quiz_attempt is one student's sitting of a quiz; it holds
-- one item_response per subiect. SINGLE_CHOICE responses reference the chosen option (auto-graded);
-- OPEN responses hold an image_key pointing to the uploaded rezolvare photo (teacher-graded).
-- awarded_points / correct stay NULL until graded.

CREATE TABLE quiz_attempts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id      BIGINT      NOT NULL REFERENCES quizzes (id),
    student_id   BIGINT      NOT NULL REFERENCES users (id),
    status       VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    started_at   TIMESTAMPTZ NOT NULL,
    submitted_at TIMESTAMPTZ,
    score        INT
);

CREATE INDEX idx_quiz_attempts_quiz_id ON quiz_attempts (quiz_id);
CREATE INDEX idx_quiz_attempts_student_id ON quiz_attempts (student_id);

CREATE TABLE item_responses (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id         BIGINT NOT NULL REFERENCES quiz_attempts (id),
    item_id            BIGINT NOT NULL REFERENCES quiz_items (id),
    selected_option_id BIGINT REFERENCES quiz_options (id),
    image_key          TEXT,
    awarded_points     INT,
    correct            BOOLEAN,
    CONSTRAINT uk_item_responses_attempt_item UNIQUE (attempt_id, item_id)
);

CREATE INDEX idx_item_responses_attempt_id ON item_responses (attempt_id);
