-- Phase 5.6: transactional outbox. A side effect owed after a transaction (e.g. the "result is ready"
-- email) is written HERE inside that same transaction — it commits with the business change or not at
-- all. A scheduled dispatcher claims due rows with FOR UPDATE SKIP LOCKED, performs the effect and marks
-- the row DONE, or backs off exponentially and dead-letters after a cap (at-least-once, visible).
-- Payloads hold ids, never personal data (GDPR erasure leaves nothing to scrub here).

CREATE TABLE outbox_event (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type      VARCHAR(80)  NOT NULL,
    payload         TEXT         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',   -- PENDING | DONE | DEAD
    attempts        INT          NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_error      TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- The dispatcher's claim query: WHERE status = 'PENDING' AND next_attempt_at <= now() ORDER BY id.
CREATE INDEX idx_outbox_claimable ON outbox_event (next_attempt_at) WHERE status = 'PENDING';
