-- E3 progressive hints. A teacher attaches up to five ordered hints to a quiz item; in PRACTICE mode a student reveals
-- them one at a time and the number revealed is kept on the student's response row (hints_used). Hints are never offered
-- in a graded test. A new table plus one ADD COLUMN ... DEFAULT <constant> (metadata-only on PostgreSQL 11+): no rewrite.
CREATE TABLE quiz_item_hints (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id  BIGINT NOT NULL REFERENCES quiz_items (id),
    position INT    NOT NULL,
    text     TEXT   NOT NULL,
    CONSTRAINT ck_quiz_item_hints_position CHECK (position >= 1),
    -- also the lookup index for "the hints of this item, in order"
    CONSTRAINT uk_quiz_item_hints_item_position UNIQUE (item_id, position)
);

ALTER TABLE item_responses
    ADD COLUMN hints_used INT NOT NULL DEFAULT 0,
    ADD CONSTRAINT ck_item_responses_hints_used CHECK (hints_used >= 0);
