-- E7 homework: a teacher assigns an existing quiz to a class with a due date. Nothing about a student's progress is
-- stored here - it is derived from their graded-test attempts at the quiz (see AssignmentProgress). One assignment per
-- (quiz, class); the deadline is soft (a late hand-in counts, flagged as late). reminder_sent_at makes the "due soon"
-- email a once-per-assignment event. Both foreign keys cascade: an assignment is meaningless without its quiz or class.
CREATE TABLE assignments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id          BIGINT      NOT NULL REFERENCES quizzes (id) ON DELETE CASCADE,
    school_class_id  BIGINT      NOT NULL REFERENCES school_classes (id) ON DELETE CASCADE,
    due_at           TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    reminder_sent_at TIMESTAMPTZ,
    CONSTRAINT uk_assignments_quiz_class UNIQUE (quiz_id, school_class_id)
);

CREATE INDEX idx_assignments_school_class ON assignments (school_class_id);

-- The reminder job looks for assignments still waiting for their reminder, ordered by deadline.
CREATE INDEX idx_assignments_reminder_due ON assignments (due_at) WHERE reminder_sent_at IS NULL;
