-- Faza 2.1a: top of the content hierarchy. A class / study year (e.g. "Clasa a 9-a")
-- that groups books and into which students enroll.
CREATE TABLE school_classes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(500)
);
