-- Faza 2.1b: books belong to a school class. A title is unique within its class.
CREATE TABLE books (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT       NOT NULL REFERENCES school_classes (id),
    title           VARCHAR(200) NOT NULL,
    description     VARCHAR(1000),
    CONSTRAINT uk_books_class_title UNIQUE (school_class_id, title)
);

CREATE INDEX idx_books_school_class_id ON books (school_class_id);
