-- Faza 2.1c: chapters belong to a book. A title is unique within its book.
CREATE TABLE chapters (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT       NOT NULL REFERENCES books (id),
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT uk_chapters_book_title UNIQUE (book_id, title)
);

CREATE INDEX idx_chapters_book_id ON chapters (book_id);
