-- Faza 2.1d: exercises are the leaf of the content hierarchy, inside a chapter.
-- statement/solution hold LaTeX (rendered with KaTeX on the frontend). `version`
-- backs JPA optimistic locking so concurrent edits conflict instead of overwriting.
CREATE TABLE exercises (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id BIGINT      NOT NULL REFERENCES chapters (id),
    statement  TEXT        NOT NULL,
    solution   TEXT,
    difficulty VARCHAR(10),
    version    BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX idx_exercises_chapter_id ON exercises (chapter_id);
