-- Faza 2.2: a student attends a school class. Unique per (student, class).
CREATE TABLE enrollments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT NOT NULL REFERENCES users (id),
    school_class_id BIGINT NOT NULL REFERENCES school_classes (id),
    CONSTRAINT uk_enrollments_student_class UNIQUE (student_id, school_class_id)
);

CREATE INDEX idx_enrollments_student_id ON enrollments (student_id);
CREATE INDEX idx_enrollments_school_class_id ON enrollments (school_class_id);
