-- Faza Quiz (Q1): the authoring model. A quiz holds ordered items (subiecte); a
-- SINGLE_CHOICE item holds ordered options with exactly one correct (enforced in the
-- service). statement/solution/option text hold LaTeX.

CREATE TABLE quizzes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    status      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT'
);

CREATE TABLE quiz_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_id    BIGINT      NOT NULL REFERENCES quizzes (id),
    position   INT         NOT NULL,
    type       VARCHAR(20) NOT NULL,
    statement  TEXT        NOT NULL,
    points     INT         NOT NULL DEFAULT 0,
    solution   TEXT
);

CREATE INDEX idx_quiz_items_quiz_id ON quiz_items (quiz_id);

CREATE TABLE quiz_options (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id  BIGINT  NOT NULL REFERENCES quiz_items (id),
    position INT     NOT NULL,
    text     TEXT    NOT NULL,
    correct  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_quiz_options_item_id ON quiz_options (item_id);
